window.esdocSearchIndex = [
  [
    "babel-plugin-transform-class-inject-directive/babel-plugin-transform-class-inject-directive/src/injectdirectiveparser.js~injectdirectiveparser",
    "class/babel-plugin-transform-class-inject-directive/src/injectDirectiveParser.js~InjectDirectiveParser.html",
    "<span>InjectDirectiveParser</span> <span class=\"search-result-import-path\">babel-plugin-transform-class-inject-directive/babel-plugin-transform-class-inject-directive/src/injectDirectiveParser.js</span>",
    "class"
  ],
  [
    "babel-plugin-transform-class-inject-directive/babel-plugin-transform-class-inject-directive/src/index.js~plugin",
    "function/index.html#static-function-plugin",
    "<span>plugin</span> <span class=\"search-result-import-path\">babel-plugin-transform-class-inject-directive/babel-plugin-transform-class-inject-directive/src/index.js</span>",
    "function"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~String",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~function",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~null",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~number",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~object",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~string",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "babel-plugin-transform-class-inject-directive/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/src/index.js",
    "file/babel-plugin-transform-class-inject-directive/src/index.js.html",
    "babel-plugin-transform-class-inject-directive/src/index.js",
    "file"
  ],
  [
    "babel-plugin-transform-class-inject-directive/src/injectdirectiveparser.js",
    "file/babel-plugin-transform-class-inject-directive/src/injectDirectiveParser.js.html",
    "babel-plugin-transform-class-inject-directive/src/injectDirectiveParser.js",
    "file"
  ],
  [
    "babel-plugin-transform-class-inject-directive/src/injectdirectiveparser.js~injectdirectiveparser#constructor",
    "class/babel-plugin-transform-class-inject-directive/src/injectDirectiveParser.js~InjectDirectiveParser.html#instance-constructor-constructor",
    "babel-plugin-transform-class-inject-directive/src/injectDirectiveParser.js~InjectDirectiveParser#constructor",
    "method"
  ],
  [
    "babel-plugin-transform-class-inject-directive/src/injectdirectiveparser.js~injectdirectiveparser#parseclassmethod",
    "class/babel-plugin-transform-class-inject-directive/src/injectDirectiveParser.js~InjectDirectiveParser.html#instance-method-parseClassMethod",
    "babel-plugin-transform-class-inject-directive/src/injectDirectiveParser.js~InjectDirectiveParser#parseClassMethod",
    "method"
  ],
  [
    "babel-plugin-transform-class-inject-directive/src/injectdirectiveparser.js~injectdirectiveparser#parsefunction",
    "class/babel-plugin-transform-class-inject-directive/src/injectDirectiveParser.js~InjectDirectiveParser.html#instance-method-parseFunction",
    "babel-plugin-transform-class-inject-directive/src/injectDirectiveParser.js~InjectDirectiveParser#parseFunction",
    "method"
  ],
  [
    "babel-plugin-transform-class-inject-directive/src/injectdirectiveparser.js~injectdirectiveparser#transform",
    "class/babel-plugin-transform-class-inject-directive/src/injectDirectiveParser.js~InjectDirectiveParser.html#instance-method-transform",
    "babel-plugin-transform-class-inject-directive/src/injectDirectiveParser.js~InjectDirectiveParser#transform",
    "method"
  ],
  [
    "babel-plugin-transform-class-inject-directive/src/typedef.js",
    "file/babel-plugin-transform-class-inject-directive/src/typedef.js.html",
    "babel-plugin-transform-class-inject-directive/src/typedef.js",
    "file"
  ],
  [
    "babel-plugin-transform-class-inject-directive/src/typedef.js~assignmentexpression",
    "https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md",
    "babel-plugin-transform-class-inject-directive/src/typedef.js~AssignmentExpression",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/src/typedef.js~babelplugintransformclassinjectdirective",
    "typedef/index.html#static-typedef-BabelPluginTransformClassInjectDirective",
    "babel-plugin-transform-class-inject-directive/src/typedef.js~BabelPluginTransformClassInjectDirective",
    "typedef"
  ],
  [
    "babel-plugin-transform-class-inject-directive/src/typedef.js~classmethodvisitor",
    "typedef/index.html#static-typedef-ClassMethodVisitor",
    "babel-plugin-transform-class-inject-directive/src/typedef.js~ClassMethodVisitor",
    "typedef"
  ],
  [
    "babel-plugin-transform-class-inject-directive/src/typedef.js~expressionstatement",
    "https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md",
    "babel-plugin-transform-class-inject-directive/src/typedef.js~ExpressionStatement",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/src/typedef.js~functiondeclarationvisitor",
    "typedef/index.html#static-typedef-FunctionDeclarationVisitor",
    "babel-plugin-transform-class-inject-directive/src/typedef.js~FunctionDeclarationVisitor",
    "typedef"
  ],
  [
    "babel-plugin-transform-class-inject-directive/src/typedef.js~functionexpressionvisitor",
    "typedef/index.html#static-typedef-FunctionExpressionVisitor",
    "babel-plugin-transform-class-inject-directive/src/typedef.js~FunctionExpressionVisitor",
    "typedef"
  ],
  [
    "babel-plugin-transform-class-inject-directive/src/typedef.js~node",
    "https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md",
    "babel-plugin-transform-class-inject-directive/src/typedef.js~Node",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/src/typedef.js~parsercallback",
    "typedef/index.html#static-typedef-ParserCallback",
    "babel-plugin-transform-class-inject-directive/src/typedef.js~ParserCallback",
    "typedef"
  ],
  [
    "babel-plugin-transform-class-inject-directive/src/typedef.js~path",
    "https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md#toc-paths",
    "babel-plugin-transform-class-inject-directive/src/typedef.js~Path",
    "external"
  ],
  [
    "babel-plugin-transform-class-inject-directive/src/typedef.js~programvisitor",
    "typedef/index.html#static-typedef-ProgramVisitor",
    "babel-plugin-transform-class-inject-directive/src/typedef.js~ProgramVisitor",
    "typedef"
  ],
  [
    "babel-plugin-transform-class-inject-directive/src/typedef.js~programvisitorfinish",
    "typedef/index.html#static-typedef-ProgramVisitorFinish",
    "babel-plugin-transform-class-inject-directive/src/typedef.js~ProgramVisitorFinish",
    "typedef"
  ],
  [
    "babel-plugin-transform-class-inject-directive/src/typedef.js~programvisitorstart",
    "typedef/index.html#static-typedef-ProgramVisitorStart",
    "babel-plugin-transform-class-inject-directive/src/typedef.js~ProgramVisitorStart",
    "typedef"
  ],
  [
    "babel-plugin-transform-class-inject-directive/src/typedef.js~visitors",
    "typedef/index.html#static-typedef-Visitors",
    "babel-plugin-transform-class-inject-directive/src/typedef.js~Visitors",
    "typedef"
  ]
]